apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-realworld-deployment
  labels:
    app: react-realworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-realworld
  template:
    metadata:
      labels:
        app: react-realworld
    spec:
      containers:
      - name: react-realworld
        image: quay.io/bluesman/react-realworld:latest
        ports:
        - containerPort: 4100
